### ISSUE TITLE
Error: Undefined method "id" for nil:NilClass

### ISSUE THREAD

**Issue by kb24x7** [cronrobot/cronrobot#252]
Error: Undefined method "id" for nil:NilClass on creating a new resource

![image](https://user-images.githubusercontent.com/61944452/132954010-f25f76b4-94ca-4081-96c8-35f8def0a0c9.png)

**Comment by kb24x7** [comment]
### Logs for www-cronrobot
```
Started GET "/dashboard/resources/new" for 103.199.182.239 at 2021-09-11 16:02:04 +0000
Cannot render console from 103.199.182.239! Allowed networks: 127.0.0.0/127.255.255.255, ::1
Processing by Dashboard::ResourcesController#new as HTML
  User Load (0.2ms)  SELECT "users".* FROM "users" WHERE "users"."uid" = ? LIMIT ?  [["uid", "google-oauth2|109354136664780264056"], ["LIMIT", 1]]
  ↳ app/controllers/concerns/www_secured.rb:10:in `logged_in_using_omniauth?'
  Project Load (0.2ms)  SELECT "projects".* FROM "projects" WHERE "projects"."user_id" = ? ORDER BY "projects"."id" ASC LIMIT ?  [["user_id", 2], ["LIMIT", 1]]
  ↳ app/controllers/dashboard_controller.rb:15:in `ensure_project_selected'
  Project Exists? (0.3ms)  SELECT 1 AS one FROM "projects" WHERE "projects"."id" = ? LIMIT ?  [["id", 2], ["LIMIT", 1]]
  ↳ app/controllers/dashboard_controller.rb:29:in `ensure_project_selected'
  Project Load (0.1ms)  SELECT "projects".* FROM "projects" WHERE "projects"."id" = ? LIMIT ?  [["id", 2], ["LIMIT", 1]]
  ↳ app/controllers/dashboard_controller.rb:33:in `ensure_project_selected'
  Project Exists? (0.2ms)  SELECT 1 AS one FROM "projects" WHERE "projects"."user_id" = ? AND "projects"."id" = ? LIMIT ?  [["user_id", 2], ["id", 2], ["LIMIT", 1]]
  ↳ app/models/user.rb:17:in `can_access_project'
  Rendering layout layouts/dashboard.html.erb
  Rendering dashboard/resources/new.html.erb within layouts/dashboard
  Rendered dashboard/resources/new.html.erb within layouts/dashboard (Duration: 3.0ms | Allocations: 371)
[Webpacker] Everything's up-to-date. Nothing to do
  Rendered layouts/_flash_errors.html.erb (Duration: 0.2ms | Allocations: 24)
  Rendered layout layouts/dashboard.html.erb (Duration: 15.1ms | Allocations: 3791)
Completed 200 OK in 42ms (Views: 16.0ms | ActiveRecord: 1.2ms | Allocations: 6995)
```

**Comment by martinlevesque** [comment]
@kb24x7 try to take the change on master https://github.com/cronrobot/cronrobot/commit/d32af3bb2baadc74ea1f44ed9ffcff21828064e1

**Comment by martinlevesque** [comment]
@kb24x7 

for the allowed error, to fix it add this in config/environments/development `config.web_console.whitelisted_ips = %w( 0.0.0.0/0 ::/0 )`
